services:
  db:
    image: mysql:8.4
    container_name: rldda_mysql
    environment:
      MYSQL_DATABASE: rldda
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    command: ["--sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"]
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data:
